import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import { OpenAI } from 'openai';

dotenv.config();

const app = express();
app.use(cors({
  origin: ['https://english-speaking-partner.vercel.app', 'http://localhost:5173'],
  methods: ['GET', 'POST'],
}));
app.use(express.json());

// Health check route so Render knows the server is alive
app.get('/', (req, res) => res.send('LingoCompanion Backend is running ✅'));
app.get('/api/chat', (req, res) => res.send('POST to this endpoint to chat ✅'));


// Initialize OpenAI client
// Note: We use the OpenAI SDK, but you can point it to OpenRouter, Google Gemini (if compatible), 
// or OpenAI itself by changing the baseURL and API Key.
const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY || 'your-api-key-here',
  baseURL: process.env.BASE_URL || 'https://api.openai.com/v1',
  defaultHeaders: {
    "HTTP-Referer": "http://localhost:5173", // Optional, for including your app on openrouter.ai rankings.
    "X-Title": "LingoCompanion", // Optional. Shows in rankings on openrouter.ai.
  }
});

app.post('/api/chat', async (req, res) => {
  try {
    const { message, history, settings } = req.body;

    if (!message) {
      return res.status(400).json({ error: 'Message is required' });
    }

    const level = settings?.level || 'intermediate';
    const voice = settings?.voice || 'female';
    const teacherName = voice === 'male' ? 'David' : 'Sarah';
    
    let difficultyParams = "";
    if (level === "beginner") {
       difficultyParams = "The user is a BEGINNER (A1-A2). Speak extremely simply, use fundamental vocabulary, and talk very slowly about basic topics. Only correct very obvious mistakes.";
    } else if (level === "intermediate") {
       difficultyParams = "The user is INTERMEDIATE (B1-B2). Use everyday vocabulary but keep the pace natural. Correct noticeable grammar mistakes.";
    } else if (level === "advanced") {
       difficultyParams = "The user is ADVANCED (C1-C2). Use complex vocabulary, idioms, and advanced phrasing. Be highly strict about their grammar and vocabulary precision in your grading.";
    }

    const DYNAMIC_PROMPT = `
You are ${teacherName}, an encouraging English speaking practice partner.
This is a spoken, voice-based conversation app, which means the text you receive is generated by speech-to-text.

${difficultyParams}

Your goals and strict rules:
1. Focus on fluency, confidence, and real-life speaking. Do not act like a strict grammar teacher.
2. DO NOT correct punctuation errors like commas, full stops, or capitalization.
3. ONLY correct mistakes that impact how the sentence is actually spoken or understood.
4. If they make a spoken mistake, keep feedback minimal. Briefly and supportively correct them at the start of your spoken 'response', then continue the conversation naturally.
5. Provide the visual correction data in the 'correction' field below. If there are no spoken mistakes, set 'correction' to null.
6. Evaluate the user's sentence strictly according to their level. Provide 'metrics' out of 100 for grammar and vocabulary.
7. NON-ENGLISH INPUT: If the user speaks in Hindi or any other language, understand their intent, but you MUST reply ONLY in English. Additionally, gently remind them in your 'response' to try speaking in English so they can practice.
8. If there is a correction, provide a short 'mistake_category' (e.g. "Verb Tense", "Articles").

You must ALWAYS respond in the following JSON format:
{
  "response": "Your spoken conversational reply (with a minimal verbal correction if needed, then engages them).",
  "correction": null OR { 
    "title": "CORRECTION: WHAT THEY SHOULD HAVE SAID", 
    "text": "A brief explanation.", 
    "mistake_category": "Category Name" 
  },
  "metrics": { "fluency": 85, "grammar": 80, "vocabulary": 75, "pronunciation": 85 }
}
`;

    // Format chat history
    const previousMessages = (history || []).map(msg => ({
      role: msg.type === 'user' ? 'user' : 'assistant',
      content: msg.type === 'user' ? msg.text : msg.text
    }));

    // Add system prompt and current message
    const messages = [
      { role: 'system', content: DYNAMIC_PROMPT },
      ...previousMessages,
      { role: 'user', content: message }
    ];

    console.log('Sending to LLM:', message);

    const completion = await openai.chat.completions.create({
      model: process.env.MODEL_NAME || 'gpt-4o-mini', // Can change to openrouter models e.g., 'google/gemini-pro'
      messages: messages,
      temperature: 0.7,
      response_format: { type: "json_object" } // Force JSON
    });

    const aiContent = completion.choices[0].message.content;
    const parsedData = JSON.parse(aiContent);

    console.log('Response from LLM:', parsedData);

    res.json(parsedData);
  } catch (error) {
    console.error('Error generating response:', error);
    res.status(500).json({ 
      error: 'Failed to generate response', 
      details: error.message 
    });
  }
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`Server is running on http://localhost:${PORT}`);
});
